# Generated by Django 5.0.14 on 2026-02-25 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("points_required", models.IntegerField(default=0)),
                (
                    "earn_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Points earned per IDR spent",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("free_breakfast", models.BooleanField(default=False)),
                ("free_upgrade", models.BooleanField(default=False)),
                ("late_checkout", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "loyalty_programs",
                "ordering": ["points_required"],
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible"),
                            ("moderate", "Moderate"),
                            ("strict", "Strict"),
                            ("non_refundable", "Non-Refundable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "days_before_checkin",
                    models.IntegerField(
                        help_text="Free cancellation if X days before check-in"
                    ),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_policies",
                        to="properties.propertytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cancellation Policies",
                "db_table": "cancellation_policies",
            },
        ),
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("free_night", "Free Night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("max_uses", models.IntegerField(default=0, help_text="0 = unlimited")),
                ("current_uses", models.IntegerField(default=0)),
                ("max_uses_per_user", models.IntegerField(default=1)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("min_nights", models.IntegerField(default=1)),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_types",
                    models.ManyToManyField(blank=True, to="properties.propertytype"),
                ),
            ],
            options={
                "db_table": "discount_coupons",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("lifetime_points", models.IntegerField(default=0)),
                ("tier_qualifying_nights", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_accounts",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive = earned, negative = redeemed"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loyalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.loyaltyaccount",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "loyalty_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTASource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Website"),
                            ("booking_com", "Booking.com"),
                            ("expedia", "Expedia"),
                            ("agoda", "Agoda"),
                            ("traveloka", "Traveloka"),
                            ("tiket_com", "Tiket.com"),
                            ("pegi_pegi", "PegiPegi"),
                            ("airbnb", "Airbnb"),
                            ("trip_com", "Trip.com"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "ota_booking_id",
                    models.CharField(
                        blank=True, help_text="Booking ID dari platform", max_length=100
                    ),
                ),
                (
                    "ota_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission rate in %, e.g., 15.00 for 15%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ota_commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total booking amount",
                        max_digits=12,
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="After commission",
                        max_digits=12,
                    ),
                ),
                ("is_synced", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ota_source",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTA Source",
                "verbose_name_plural": "OTA Sources",
                "db_table": "ota_sources",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, help_text="Room price x nights", max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="PPN 11%", max_digits=12
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Service 5-10%",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("virtual_account", "Virtual Account"),
                            ("qris", "QRIS"),
                            ("ota_booking", "OTA Platform"),
                            ("gopay", "GoPay"),
                            ("ovo", "OVO"),
                            ("dana", "DANA"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                ("stripe_charge_id", models.CharField(blank=True, max_length=200)),
                ("midtrans_order_id", models.CharField(blank=True, max_length=200)),
                ("xendit_invoice_id", models.CharField(blank=True, max_length=200)),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("refund_reason", models.TextField(blank=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("bill_to_name", models.CharField(max_length=200)),
                ("bill_to_email", models.EmailField(max_length=254)),
                ("bill_to_address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DynamicPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("low", "Low Season"),
                            ("mid", "Mid Season"),
                            ("high", "High Season"),
                            ("peak", "Peak / Holiday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="1.0 = base price, 1.5 = 50% increase, 0.8 = 20% discount",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.50")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "weekend_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority overrides lower"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_prices",
                        to="properties.propertytype",
                    ),
                ),
            ],
            options={
                "db_table": "dynamic_pricing",
                "ordering": ["-priority", "start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date", "is_active"],
                        name="dynamic_pri_start_d_952f1e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_status_426d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="payments_payment_ee488d_idx"
            ),
        ),
    ]
